export const techs: string[] = [
  "React",
  "Vue",
  "Svelvte",
  "NodeJs",
  "Golang",
  "Ruby",
  "Svelvte",
  "Mongodb",
  "PostGresQl",
  "Python",
  "ElasticSearch",
  "AWS",
  "NextJS",
  "NuxtJS",
  "MySQL",
  "Javascript",
  "Typescript",
];

export const jobTitles: string[] = [
  "Software Engineer",
  "Fullstack Developer",
  "Fullstack Engineer",
  "IOS Developer",
  "UI Designer",
  "Android Developer",
  "Frontend Developer",
  "Backend Developer",
  "Tester",
  "React Developer",
  "Project Manager",
  "UX Designer",
  "Junior Full Stack Developer",
];
