name: Deploy master

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.15.1"

      - name: Install dependencies
        run: yarn install

      - name: Generate deployment package
        run: yarn clean && yarn build && yarn dist

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: zcrapper
          environment_name: Zcrapper-env
          version_label: 1.0.1
          region: ap-southeast-1
          deployment_package: deploy_artifacts.zip
